name: Test

on: [push, pull_request]

jobs:
  test-bins:
    name: Test Bins
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9']
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Prepare dependencies
        run: make prepare

      - name: Check packages
        run: make check

      - name: Install packages
        run: make install
